# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Jekyll Metro'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
url:              ''
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Abdel Raoof Olakara'
linkedin:       'http://zhufengdaaa.github.io/'
twitter:        'http://zhufengdaaa.github.io/'
facebook:       'http://zhufengdaaa.github.io/'
gplus:          'https://plus.google.com/u/0/116811442309236138007/posts/p/pub'

# Google Analytics
gahandler: 'UA-52149651-1'

# Disqus
#disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
