# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Le Petit Prince'
tagline:          "Le Petit Prince's Planet" 
description:      'A Sample blog using Jekyll Metro'
url:              ''
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url : /search

# Author Details
author:         'ZhuFengdaaa'
linkedin:       'http://zhufengdaaa.github.io/'
twitter:        'http://zhufengdaaa.github.io/'
facebook:       'http://zhufengdaaa.github.io/'
gplus:          'https://plus.google.com/u/0/116811442309236138007/about/p/pub'

# Google Analytics
gahandler: 'UA-58081640-1'

footer-links:
  dribbble: 
  email: zhufengdaaa@gmail.com
  facebook: 
  flickr: 
  github: ZhuFengdaaa
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: https://plus.google.com/u/0/116811442309236138007/about/p/pub
  twitter: None
  stackoverflow: #users/4388898/peter-zhu # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Disqus
#disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
